DROP TABLE IF EXISTS "crm_deals" CASCADE;
DROP TABLE IF EXISTS "crm_sources" CASCADE;
DROP TABLE IF EXISTS "crm_source_config" CASCADE;
DROP TABLE IF EXISTS "crm_stages" CASCADE;
DROP TABLE IF EXISTS "crm_pipelines" CASCADE;
DROP TABLE IF EXISTS "crm_connections" CASCADE;
